#!/usr/bin/env bash
set -euo pipefail

# MP-BUILD-HOOKSINSTALLGUARD-001
# Verifies that git hooks are actually installed in the CURRENT worktree.
# core.hooksPath resolves per-worktree to .husky/_/, which is generated by
# `npm install` (via package.json's "prepare": "husky" script) and is
# gitignored — not committed. Any worktree/clone that pushes before
# `npm install` has completed has this directory absent, and git silently
# runs zero hooks with no error or warning. This script makes that gap loud.

REPO_ROOT=$(git rev-parse --show-toplevel)

HUSKY_SH="$REPO_ROOT/.husky/_/husky.sh"
PRE_PUSH_SHIM="$REPO_ROOT/.husky/_/pre-push"

if [ ! -f "$HUSKY_SH" ] || [ ! -f "$PRE_PUSH_SHIM" ]; then
  echo "CHECK-HOOKS: Git hooks are not installed in this worktree — pushes will" >&2
  echo "CHECK-HOOKS: silently skip all safety gates including the protected-baseline" >&2
  echo "CHECK-HOOKS: sync-compete check. Run \`npx husky\` (or \`npm install\`) before pushing." >&2
  exit 1
fi

exit 0
