import { NextRequest, NextResponse } from "next/server";
import { createAuthenticatedServerClient, createSupabaseServerClient } from "@/core/supabaseServer";

export const dynamic = "force-dynamic";

interface RegisterBody {
  token: string;
}

export async function POST(request: NextRequest) {
  const supabase = createAuthenticatedServerClient();
  const { data: { user }, error: authError } = await supabase.auth.getUser();

  if (authError || !user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  let body: RegisterBody;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const { token } = body;
  if (typeof token !== "string" || token.length < 20 || token.length > 4096) {
    return NextResponse.json({ error: "Invalid token" }, { status: 400 });
  }

  // Delete any stale row owned by another user for this token. An FCM token is
  // a bearer credential generated by the device and tied to the app's service
  // account; reassignment to the most recent registrant is safe.
  const serviceRoleClient = createSupabaseServerClient();
  const { error: deleteError } = await serviceRoleClient
    .from("fcm_tokens")
    .delete()
    .eq("token", token)
    .neq("user_id", user.id);

  if (deleteError) {
    console.error("[push/fcm-register] failed to remove conflicting token:", deleteError);
  }

  const { error } = await supabase.from("fcm_tokens").upsert(
    {
      user_id: user.id,
      token,
      updated_at: new Date().toISOString(),
    },
    {
      onConflict: "user_id,token",
      ignoreDuplicates: false,
    }
  );

  if (error) {
    console.error("[push/fcm-register] upsert failed:", error);
    return NextResponse.json({ error: "Failed to save token" }, { status: 500 });
  }

  return NextResponse.json({ ok: true }, { status: 200 });
}
